title: Accelerating Mathematical Discovery
subtitle: A Crash Course in AI and Computation
email: aimathconference@gmail.com
description: This work is supported by the AI For Math Fund, which is run by Renaissance Philanthropy and funded by XTX Markets

theme: minima

plugins:
  - jekyll-feed
